const MyFavoriteVolunteer_DataList = [
  {
    id: 1,
    title: "아직 엄마 품이 필요한 고양이들에게 사랑을 나누어 주세요.",
    organ: "사랑냥이 보호센터",
    recruitment_cur: 40,
    recruitment_limit: 50,
    completed: 60,
  },
  {
    id: 2,
    title: "청소 및 산책 봉사자 모집.",
    organ: "광주동물보호협회 위드",
    recruitment_cur: 1,
    recruitment_limit: 10,
    completed: 10,
  },
  {
    id: 3,
    title: "중·대형견 미용 봉사자 모십니다. 자격증 필수! ",
    organ: "한사랑 아름다운 우리 보호소",
    recruitment_cur: 3,
    recruitment_limit: 10,
    completed: 30,
  },
  {
    id: 4,
    title: "아직 엄마 품이 필요한 고양이들에게 사랑을 나누어 주세요.",
    organ: "사랑냥이 보호센터",
    recruitment_cur: 40,
    recruitment_limit: 50,
    completed: 80,
  },
  {
    id: 5,
    title: "청소 및 산책 봉사자 모집.",
    organ: "광주동물보호협회 위드",
    recruitment_cur: 1,
    recruitment_limit: 10,
    completed: 10,
  },
  {
    id: 6,
    title: "중·대형견 미용 봉사자 모십니다. 자격증 필수! ",
    organ: "한사랑 아름다운 우리 보호소",
    recruitment_cur: 10,
    recruitment_limit: 10,
    completed: 100,
  },
  {
    id: 7,
    title: "아직 엄마 품이 필요한 고양이들에게 사랑을 나누어 주세요.",
    organ: "사랑냥이 보호센터",
    recruitment_cur: 50,
    recruitment_limit: 50,
    completed: 100,
  },
  {
    id: 8,
    title: "청소 및 산책 봉사자 모집.",
    organ: "광주동물보호협회 위드",
    recruitment_cur: 1,
    recruitment_limit: 10,
    completed: 10,
  },
  {
    id: 9,
    title: "중·대형견 미용 봉사자 모십니다. 자격증 필수! ",
    organ: "한사랑 아름다운 우리 보호소",
    recruitment_cur: 3,
    recruitment_limit: 10,
    completed: 30,
  },
];

export { MyFavoriteVolunteer_DataList };
