export const VolunteerList = [
    {
        vol_id:1,
        vol_img: process.env.PUBLIC_URL + `/assets/main/vol_img_1.png`, 
        title : "경주 보호소 겨울철 유기견 봉사 모집합니다",
        organ : "경주 사랑 유기견 보호소",
        recruitment_cur: 1,
        recruitment_limit: 10,
        completed : 10,
    },
    {
        vol_id:2,
        vol_img: process.env.PUBLIC_URL + `/assets/main/vol_img_2.png`, 
        title : "청소 및 산책 봉사자 모집",
        organ : "광주동물보호협회 위드",
        recruitment_cur: 4,
        recruitment_limit: 20,
        completed : 20,
    },
    {
        vol_id:3,
        vol_img: process.env.PUBLIC_URL + `/assets/main/vol_img_3.png`, 
        title : "중·대형견 미용 봉사자 모십니다. 자격증 필수! ",
        organ : "한사랑 아름다운 우리 보호소",
        recruitment_cur: 8,
        recruitment_limit: 10,
        completed : 80,
    },
    {
        vol_id:4,
        vol_img: process.env.PUBLIC_URL + `/assets/main/vol_img_4.png`, 
        title : "즐거운 봉사의 시작! 처음 봉사하는 사람들 모여라!",
        organ : "광주동물보호협회 위드",
        recruitment_cur: 20,
        recruitment_limit: 40,
        completed : 50,
    },
    {
        vol_id:5,
        vol_img: process.env.PUBLIC_URL + `/assets/main/vol_img_1.png`, 
        title : "경주 보호소 겨울철 유기견 봉사 모집합니다",
        organ : "경주 사랑 유기견 보호소",
        recruitment_cur: 5,
        recruitment_limit: 20,
        completed : 25,
    },
    ]